#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXtst
Version  : 1.2.2
Release  : 8
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXtst-1.2.2.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXtst-1.2.2.tar.bz2
Summary  : The Xtst Library
Group    : Development/Tools
License  : MIT
Requires: libXtst-lib
Requires: libXtst-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(inputproto)
BuildRequires : pkgconfig(recordproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xmlto

%description
libXtst provides the Xlib-based client API for the XTEST & RECORD extensions.
The XTEST extension is a minimal set of client and server extensions
required to completely test the X11 server with no user intervention.
This extension is not intended to support general journaling and
playback of user actions.

%package dev
Summary: dev components for the libXtst package.
Group: Development
Requires: libXtst-lib

%description dev
dev components for the libXtst package.


%package doc
Summary: doc components for the libXtst package.
Group: Documentation

%description doc
doc components for the libXtst package.


%package lib
Summary: lib components for the libXtst package.
Group: Libraries

%description lib
lib components for the libXtst package.


%prep
%setup -q -n libXtst-1.2.2

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XTest.h
/usr/include/X11/extensions/record.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXtst/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
